language: php

php:
    - "7.4"
    #- "8.0"

branches:
  only:
  - app/Http/Controllers
  - app/Models/Yatzy
  - app/Models/ResultsHandler.php

before_script:
    #- make install check
    - make install
    - composer install
    - cp .env.travis .env
    - php artisan key:generate

script:
    - make test
